pika-fastfetch-gui usr/bin/
pika_fastfetch_gui.py usr/share/pika-fastfetch-gui/
style.css usr/share/pika-fastfetch-gui/
scripts/collect.sh usr/share/pika-fastfetch-gui/scripts/
pika-fastfetch-gui.desktop usr/share/applications/
data/icons/hicolor/scalable/apps/pika-fastfetch-gui.svg usr/share/icons/hicolor/scalable/apps/
README.md usr/share/doc/pika-fastfetch-gui/
LICENSE usr/share/doc/pika-fastfetch-gui/
